server:
  port: 8001
  servlet:
    context-path: /member
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_member?autoReconnect=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: train
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.study.train.member.mapper: trace